# Navbar Menus
social:
  - name: Instagram
    url: "https://www.instagram.com/upflinkoping/"
    pre: "fab fa-instagram"
    weight: 1
  - name: Facebook
    url: "https://www.facebook.com/UPFlinkoping"
    pre: "fab fa-facebook"
    weight: 2
  - name: LinkedIn
    url: "https://www.linkedin.com/company/upf-linkoping/"
    pre: "fab fa-linkedin"
    weight: 3
  - name: Cardskipper
    url: "https://apply.cardskipper.se/hr3"
    pre: "images/icons/cardskipper"
    weight: 4
main:
  - name: Home
    url: ""
    weight: 1
  - name: Board
    url: /board/2023
    weight: 3
  - name: Calendar
    url: /calendar
    weight: 4
  - name: Portfolio
    url: /portfolio
    weight: 5
  - name: Learn More
    url: "https://linktr.ee/upflinkoping"
    weight: 6