baseURL: https://upflinkoping.org/
languageCode: en-us
title: UPF Linköping | Student Association of Foreign Affairs
summarylength: 25

register: &register "https://apply.cardskipper.se/hr3"
linktree: &linktree "https://linktr.ee/upflinkoping"

permalinks:
  portfolio: /:sections[1:]/:slug/
  

# Site Menus
menu:
  # Navbar Menus

  social:
    - name: Instagram
      url: "https://www.instagram.com/upflinkoping/"
      pre: "fab fa-instagram"
      weight: 1

    - name: Facebook
      url: "https://www.facebook.com/UPFlinkoping"
      pre: "fab fa-facebook"
      weight: 2

    - name: LinkedIn
      url: "https://www.linkedin.com/company/upf-linkoping/"
      pre: "fab fa-linkedin"
      weight: 3

    - name: Cardskipper
      url: *register
      pre: "images/icons/cardskipper"
      weight: 4

  main:
    - name: Home
      url: ""
      weight: 1

    #- name: About
    #url: about
    #weight: 2

    - name: Board
      url: /board/2022
      weight: 3

    - name: Calendar
      url: /calendar
      weight: 4

    - name: Portfolio
      url: /portfolio
      weight: 5

    - name: Learn More
      url: *linktree
      weight: 6

# Site Params
params:
  # logo: /images/logo.png
  logo: "images/upf/upf-icon"
  logo_footer: "images/upf/upf-logo"
  dateFormat: 26 FEB 1994
  # Site Params
  # description: Roxo Hugo themes | Design Agency Template by StaticMania
  author: StaticMania
  # Google Analitycs
  googleAnalitycsID: Your ID
  # We're using formspree.io for form handling, paste your formspree url below
  fabform: "https://fabform.io/f/USAg2Jl"

  main_behold_id: 6CW7rm0ZnxxUnu9i7sxM

  insta_placeholder: More on Instagram
  single_lightwidget_id: b656bb389a0257d7a8b4acf4532c0b42

  ignore:
    - portfolio
  
  cover_dimens:
    width: 960
    height: 960

  # Navbar Action Button
  navAction:
    status: true
    name: Learn More
    url: *linktree

  # Banner Section
  banner:
    enable: true
    #background_image   : images/upf/background.png
    title: UPF Linköping
    heading: Student Association of Foreign Affairs
    primary_button: See what we do
    primary_button_url: portfolio
    secondary_button: Become a member
    secondary_button_url: *register

  call_to_action:
    enable: true
    background_image: images/backgrounds/cta-background.jpg
    title: become a member today
    primary_button: Join us
    primary_button_url: *register
    secondary_button: Not Convinced
    secondary_button_url: *register

  error:
    code: 404
    text: PAGE NOT FOUND
    button:
      url: /
      text: Go back home

  footer:
    # Footer Contact Info
    contactInfo:
      title: Contact Info
      address: "Kårallen, Linköping,<br>58183, SE"
      email: info@upflinkoping.org

    # Footer Sitemap
    sitemap:
      title: Sitemap
      link:
        # - name: About Company
        # url: about
        - name: Projects
          url: portfolio
        - name: Board
          url: board/2022
        #- name: Contact
        #  url: contact
        - name: Calendar
          url: calendar

    # Footer Social Media
    social:
      title: Social Media
      link:
        - name: Instagram
          url: "https://www.instagram.com/upflinkoping/"
        - name: Linkedin
          url: "https://www.linkedin.com/company/upf-linkoping/"
        - name: Facebook
          url: "https://www.facebook.com/UPFlinkoping"
        - name: Cardskipper
          url: *register

    copyright:
      text: UPF Linköping
      rights: Copyright ©
      template:
        text: "- based on a template by"
        link: StaticMania

taxonomies:
  category: categories
  tag: tags
  board: board

module:
  mounts:
    - source: assets
      target: assets
    - source: _huge
      target: assets/_huge
  imports:
    - path: "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
    - path: github.com/UtkarshVerma/hugo-modules/svg-icon-system
    #- path: github.com/theNewDynamic/huge

_build:
  publishResources: false