[build]
publish = "public"
command = "hugo --minify"

#[build.environment]
#  GO_VERSION = "1.14"
#  HUGO_VERSION = "0.108.0"

[context]

[context.production]

[context.production.environment]
HUGO_ENV = "production"
